### ISSUE TITLE
Assertion failed: (NO), function -[RNFirebaseCrashReport report:]

### ISSUE THREAD

**Issue by annelorraineuy** [ianlin/react-native-firebase-crash-report#10]
This is my first time integrating Firebase Crash so I hope someone can help me. My XCode stops running because of the following error:

```
2017-02-13 11:44:27.880900 rooplayNativeMock3[7547:1469600] Testing Firebase crash reporting....
Assertion failed: (NO), function -[RNFirebaseCrashReport report:], file /Users/annelorraineuy/projects/rooplayNativeMock3/node_modules/react-native-firebase-crash-report/ios/RNFirebaseCrashReport/RNFirebaseCrashReport.m, line 37.
warning: could not load any Objective-C class information. This will significantly reduce the quality of type information available.
(lldb) 
```

I am testing out this package by putting it into my app init saga. Like this:
```
import FirebaseCrash from 'react-native-firebase-crash-report';

export function* initApp(clientAuth, clientApi) {
      ...
      FirebaseCrash.logcat('Testing Firebase crash reporting....');
      FirebaseCrash.report('Please receive this on the console.'); // <- this line triggers it
      ...
}
```

What is this line `assert(NO)` here under report for? https://github.com/ianlin/react-native-firebase-crash-report/blob/master/ios/RNFirebaseCrashReport/RNFirebaseCrashReport.m#L37

**Comment by ianlin** [comment]
Hey @annelorraineuy, the `report` api is intended to make the crash, you can find it on the [Firebase Crash Reporting Document][1]

So normally you don't have to call this api unless you are debugging and you want to see the logs on the Firebase console

[1]: https://firebase.google.com/docs/crash/ios#create_your_first_error

**Comment by annelorraineuy** [comment]
Oh.. Okay, thank you for pointing that out!

**Comment by ianlin** [comment]
f2fe9bafba6bc006fbe739c8017cff8cbbf450ce updates the README that indicates `report` API will result in app crash on iOS
