### ISSUE TITLE
Android config lacks manual instructions

### ISSUE THREAD

**Issue by annelorraineuy** [ianlin/react-native-firebase-crash-report#11]
I am not sure why `react-native link` did not automatically add this part for me. I've got this package working in tandem with [react-native-firebase-analytics](https://github.com/evollu/react-native-firebase-analytics), so thanks for this!

Anyway, just sharing in case someone else runs into the error where `FirebaseCrash is undefined` on android, and looking to use both analytics and crash reporting together. Basically manual install instructions:

**app/build.gradle**
```
dependencies {
  ...
  compile project(':react-native-firebase-analytics')
  compile project(':react-native-firebase-crash-report') <-- add this
  ...
}
```

**settings.gradle**
```
include ':react-native-firebase-analytics'
project(':react-native-firebase-analytics').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase-analytics/android')

// add everything below this
include ':react-native-firebase-crash-report'
project(':react-native-firebase-crash-report').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase-crash-report/android')
```

**MainApplication.java**
```
...
import com.ianlin.RNFirebaseCrashReport.RNFirebaseCrashReportPackage; <-- add this
...

@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new FIRAnalyticsPackage(),
            ...
            new RNFirebaseCrashReportPackage(), <-- add this
            ...
      );
 }
```

**Comment by ianlin** [comment]
Thanks for this, you are not the only one who run into this - `rnpm link` or `react-native link` did not add the `compile` line in `app/build.gradle`. Will add these manual guides in readme soon, cheers.
