### ISSUE TITLE
 Why Android installation instructions are different that Firebase Default?

### ISSUE THREAD

**Issue by rturk** [ianlin/react-native-firebase-crash-report#4]
Installation instructions are slightly different than:
https://firebase.google.com/docs/crash/android

**Specially:**
Add the dependency for Crash Reporting to your app-level build.gradle file:
compile 'com.google.firebase:firebase-crash:9.2.1'

Is this a typo, or intentional?

**Comment by ianlin** [comment]
Hey @rturk, it's specified in this module's [build.gradle](https://github.com/ianlin/react-native-firebase-crash-report/blob/master/android/build.gradle) therefore in your react-native android there is no need to add this again. Let me know if it works for you. :)
