### ISSUE TITLE
React native is now at RN30 - is this correct:  compile 'com.facebook.react:react-native:0.20.+'?: 

### ISSUE THREAD

**Issue by rturk** [ianlin/react-native-firebase-crash-report#5]
Hi,
I'm using RN30,

Is this correct or this package is only compatible with RN20?
 compile 'com.facebook.react:react-native:0.20.+'?: 
https://github.com/ianlin/react-native-firebase-crash-report/blob/master/android/build.gradle#L16

tks

**Comment by ianlin** [comment]
ah I think it was a copy-paste problem. This package indeed doesn't depend on specific RN version. Thanks for pointing this out will be changing this later.
