### ISSUE TITLE
Android installation fails.

### ISSUE THREAD

**Issue by ddobby94** [ianlin/react-native-firebase-crash-report#9]
After npm install && rnpm link and putting the dependencies inside the root level build.gradle and to the bottom of the app level build.gradle, I am getting this error: 

```
:app:compileDebugJavaWithJavac
C:\medicall\android\app\src\main\java\co\my\package\MainActivity.java:6: error: package com
.ianlin.RNFirebaseCrashReport does not exist
import com.ianlin.RNFirebaseCrashReport.RNFirebaseCrashReportPackage;
                                       ^
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.
```

I even tried inserting it inside the settings.gradle, but did not help neither. 

React-Native : 0.40.0,
react-native-firebase-crash-report: 1.2.0,
latest google repository and play services in the android studio

Any ideas on this issue? 
Thanks in advance.

**Comment by ddobby94** [comment]
UPDATE: swithced to rn: 0.41.0, but I am still getting the same error, just as above.

**Comment by ianlin** [comment]
Hey @ddobby94, can you show your `settings.gradle`? There should be these two lines:

```gradle
include ':react-native-firebase-crash-report'
project(':react-native-firebase-crash-report').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase-crash-report/android')
```

**Comment by ddobby94** [comment]
thanks for the quick reply, @ianlin 
Here is my settings.gradle: 

```
...
include ':react-native-firebase-crash-report'
project(':react-native-firebase-crash-report').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase-crash-report/android')
...
```

**Comment by ianlin** [comment]
It looks right. Also can you please show your `android/build.gradle` and `android/app/build.gradle`? Cheers.

**Comment by ddobby94** [comment]
app lvl:
```
dependencies {
    ...
    compile "com.google.firebase:firebase-messaging:10.0.0"
    compile "com.google.android.gms:play-services-location:10.0.0"
    compile "com.facebook.react:react-native:+"  // From node_modules
}

apply plugin: 'com.google.gms.google-services'

```

root lvl: 

```
dependencies {
        classpath 'com.android.tools.build:gradle:2.0.0'
        classpath 'com.google.gms:google-services:3.0.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
```

**Comment by ianlin** [comment]
In your app level's build.gradle there should be this line:

```gradle
compile project(':react-native-firebase-crash-report')
```

Normally it's added automatically via rnpm link, did you successfully run `rnpm link`?

**Comment by ddobby94** [comment]
@ianlin Yes! That's it! The build is now good! 

And answering your question: I have runned the rnpm link, but it only put 
`import com.ianlin.RNFirebaseCrashReport.RNFirebaseCrashReportPackage;`
inside **MainActivity.java**, 

but the `compile project(':react-native-firebase-crash-report')`
was missing from **app/build.gradle**.

I think you could add this line to the android installation too:

- In `android/setting.gradle` 
```
include ':react-native-firebase-crash-report'
project(':react-native-firebase-crash-report').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase-crash-report/android')
```

Thanks for the help!
